version: '3'

services:
  backend:
    build:
      context: ./system-car
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./system-car-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
